### ISSUE TITLE
Bring Up To Standard

### ISSUE THREAD

**Issue by mecha** [Dhii/validation-abstract#8]
The classes do not reflect the interfaces, which their descendants will eventually implement.

- [x] The message of the exception that the validator throws is not internationalized.
- [ ] [`AbstractValidationException`] is not aware of the validator instance that threw/caused/encountered the exception.

[`AbstractValidationException`]:                 https://github.com/Dhii/validation-abstract/blob/develop/src/Exception/AbstractValidationException.php

**Comment by XedinUnknown** [comment]
Resolved in PR #10.
