### ISSUE TITLE
Add base functionality for composite validation

### ISSUE THREAD

**Issue by mecha** [Dhii/validation-abstract#9]
Composite validation here refers to the process of performing validation using multiple validators.

The recommended approach is the use a list of children validators and compile their validation errors into a single list that can be retrieved via [`_getValidationErrors()`]. This would allow implementations to benefit from [`AbstractValidator`] as their ancestor while also fulfilling the [`_getValidationErrors()`] method via the trait.

[`AbstractValidator`]: ../blob/master/src/AbstractValidator.php
[`_getValidationErrors()`]: ../blob/master/src/AbstractValidator.php#L75

**Comment by XedinUnknown** [comment]
Done in 0e7b2a089addf23088cb433a957949f926743e65 (PR #10) and dhii/validation-base@7c4e948a0951af7d91305dfb6e4f3629717b5b0c (PR dhii/validation-base#4).
